services:
  cash-trackr:
    container_name: CashTrackrApplication
    image: dockerlucasoliveira/cashtrackr:latest
    ports:
      - 8080:8080
    depends_on:
      sql-db:
        condition: service_healthy

  sql-db:
    container_name: SqlServerDb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 1433:1433
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: root@strongPassword
    healthcheck:
      test: ["CMD-SHELL", "(/bin/bash -c 'echo > /dev/tcp/localhost/1433') || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  no-sql-db:
    container_name: RedisDb
    image: redis:latest
    ports:
        - 6379:6379
    restart: always  