services:
  sql-db-cash-trackr:
    container_name: CashTrackrSqlServer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 1433:1433
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: root@strongPassword
        MSSQL_PID: Developer

  no-sql-db-cash-trackr:
    container_name: CashTrackrRedis
    image: redis:latest
    ports:
        - 6379:6379
    restart: always  